/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratosportuguesesaviadores;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas_g_flores
 */
public class Ficha extends javax.swing.JFrame {
    
    static Personagens perso;
    static int id_do_personagem;
    static boolean editar;

    static int getIdDoPersonagem() {
       return id_do_personagem;
    }
    static boolean getEditar(){
    return editar;
    }
    

    /**
     * Creates new form CriacaoDePersonagem
     */
    public Ficha() {
        initComponents();
        Ficha.editar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNomeDoPersonagem = new javax.swing.JLabel();
        campoClasse = new javax.swing.JLabel();
        campoRaca = new javax.swing.JLabel();
        campoNivel = new javax.swing.JLabel();
        campoNomeDoJogador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoVida = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        campoParaId = new javax.swing.JTextField();
        campoListaDeMagia = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        campoParaColocarONomeDaMagia = new javax.swing.JTextField();
        campoForca = new javax.swing.JLabel();
        campoDex = new javax.swing.JLabel();
        campoConstituicao = new javax.swing.JLabel();
        campoInteligencia = new javax.swing.JLabel();
        campoSabedoria = new javax.swing.JLabel();
        campoCarisma = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        numeroIndicaVidaChange = new javax.swing.JLabel();
        VidaDosMaximo = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        campoModStr = new javax.swing.JLabel();
        campoModDex = new javax.swing.JLabel();
        campoModCons = new javax.swing.JLabel();
        campoModInt = new javax.swing.JLabel();
        campoModSab = new javax.swing.JLabel();
        campoModCha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("Criar personagem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("selecionar personagem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Força");

        jLabel2.setText("Dextreza");

        jLabel3.setText("constituição");

        jLabel4.setText("inteligência");

        jLabel5.setText("sabedoria");

        jLabel6.setText("Carisma");

        campoNomeDoPersonagem.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoNomeDoPersonagem.setText("personagem");

        campoClasse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoClasse.setText("jLabel8");

        campoRaca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoRaca.setText("jLabel9");

        campoNivel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoNivel.setText("jLabel10");

        campoNomeDoJogador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campoNomeDoJogador.setText("nome do jogador");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Vida");

        campoVida.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        campoVida.setText("Vida atual");

        jButton3.setText("melhorei");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("piorei");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        campoParaId.setText("colocar id do personagem");
        campoParaId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoParaIdMouseClicked(evt);
            }
        });
        campoParaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoParaIdActionPerformed(evt);
            }
        });

        campoListaDeMagia.setText("lista de magia");

        jButton5.setText("selecionar magia");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        campoParaColocarONomeDaMagia.setText("id da magia");
        campoParaColocarONomeDaMagia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoParaColocarONomeDaMagiaMouseClicked(evt);
            }
        });
        campoParaColocarONomeDaMagia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoParaColocarONomeDaMagiaActionPerformed(evt);
            }
        });

        campoForca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoForca.setText("jLabel17");

        campoDex.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoDex.setText("jLabel18");

        campoConstituicao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoConstituicao.setText("jLabel19");

        campoInteligencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoInteligencia.setText("jLabel20");

        campoSabedoria.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoSabedoria.setText("jLabel21");

        campoCarisma.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        campoCarisma.setText("jLabel22");

        jButton6.setText("mostrar os personagens");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("setar vida");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        numeroIndicaVidaChange.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        numeroIndicaVidaChange.setText("0");

        VidaDosMaximo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        VidaDosMaximo.setText("0");

        jButton8.setText("criar magia");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("mostrar lista");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("editar personagem");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        campoModStr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModStr.setText("jLabel7");

        campoModDex.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModDex.setText("jLabel8");

        campoModCons.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModCons.setText("jLabel9");

        campoModInt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModInt.setText("jLabel10");

        campoModSab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModSab.setText("jLabel11");

        campoModCha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        campoModCha.setText("jLabel13");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel7.setText("Classe");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel8.setText("Rassa");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setText("Nivel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(campoClasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(campoRaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(campoNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoNomeDoJogador)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoListaDeMagia, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addComponent(campoParaColocarONomeDaMagia, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(campoForca)
                            .addComponent(campoDex)
                            .addComponent(campoConstituicao)
                            .addComponent(campoInteligencia)
                            .addComponent(campoSabedoria)
                            .addComponent(campoCarisma)
                            .addComponent(jButton8)
                            .addComponent(campoModStr)
                            .addComponent(campoModDex)
                            .addComponent(campoModCons)
                            .addComponent(campoModInt)
                            .addComponent(campoModSab)
                            .addComponent(campoModCha)
                            .addComponent(campoNomeDoPersonagem)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(campoVida)
                                    .addComponent(numeroIndicaVidaChange)
                                    .addComponent(jButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(campoParaId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton2))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(501, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VidaDosMaximo)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(campoClasse)
                    .addComponent(campoNivel)
                    .addComponent(campoRaca))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoModStr)
                        .addGap(18, 18, 18)
                        .addComponent(campoForca))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(VidaDosMaximo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoVida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(campoModDex)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numeroIndicaVidaChange)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(campoListaDeMagia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoDex)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoModCons)
                                .addGap(14, 14, 14)
                                .addComponent(campoConstituicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoModInt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoInteligencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(campoModSab)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoSabedoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoModCha)
                                .addGap(18, 18, 18)
                                .addComponent(campoCarisma)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(campoParaColocarONomeDaMagia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton5)
                                            .addComponent(jButton9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(campoParaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton6)
                                            .addComponent(jButton1))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(47, 47, 47))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeDoPersonagem, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(campoNomeDoJogador, javax.swing.GroupLayout.Alignment.CENTER))
                .addGap(674, 674, 674))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoParaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoParaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoParaIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Ficha.editar = false;
        CriadorDePersonagem cdp = new CriadorDePersonagem();
        cdp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Banco.visualizarPersonagens(Cadastro.getNomeDoUsuario());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(campoParaId.getText().equals("") || campoParaId.getText().equals("colocar id do personagem")){
           JOptionPane.showMessageDialog(this, "coloca um id meo"); 
        }else{
        Personagens p = Banco.pegarOsBagueteDoPersonagem(Integer.parseInt(campoParaId.getText()));
        campoNomeDoPersonagem.setText("" + p.nome);
        campoNomeDoJogador.setText("" + p.nome_do_usuario);
        campoRaca.setText("" + p.raca);
        campoClasse.setText("" + p.classe);
        campoCarisma.setText("" + p.status.cha);
        campoConstituicao.setText("" + p.status.cons);
        campoDex.setText("" + p.status.dex);
        campoForca.setText("" + p.status.str);
        campoInteligencia.setText("" + p.status.inte);
        campoSabedoria.setText("" + p.status.sab);
        campoVida.setText("" + p.vida);
        campoNivel.setText("" + p.nivel);
        VidaDosMaximo.setText("" + p.vidaMaxima);
        campoModStr.setText((p.status.str-10)/2+"");
        campoModDex.setText((p.status.dex-10)/2+"");
        campoModCons.setText((p.status.cons-10)/2+"");
        campoModInt.setText((p.status.inte-10)/2+"");
        campoModSab.setText((p.status.sab-10)/2+"");
        campoModCha.setText((p.status.cha-10)/2+"");
        Ficha.id_do_personagem = p.id;
        Ficha.perso = p;
        }
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (!campoNomeDoPersonagem.getText().equals("personagem")) {
            int vm = Integer.parseInt(numeroIndicaVidaChange.getText());
            int va  = Integer.parseInt(campoVida.getText());
            if (va+vm < 0) {
                JOptionPane.showMessageDialog(this, "Parece que fudeu");
                campoVida.setText(0 + "");
            } else {
                campoVida.setText(va+vm+  "");
            }

            Banco.mudarVidaDoPersonagem(vm, campoNomeDoPersonagem.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Mano, pega um personagem primerio");
            numeroIndicaVidaChange.setText(0 + "");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int vm = Integer.parseInt(numeroIndicaVidaChange.getText());
        vm--;
        numeroIndicaVidaChange.setText("" + vm);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void campoParaColocarONomeDaMagiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoParaColocarONomeDaMagiaActionPerformed
        
    }//GEN-LAST:event_campoParaColocarONomeDaMagiaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int vm = Integer.parseInt(numeroIndicaVidaChange.getText());
        vm++;
        numeroIndicaVidaChange.setText("" + vm);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (!campoNomeDoPersonagem.getText().equals("personagem")) {
            CriadrorDeMagia mag = new CriadrorDeMagia();
            mag.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "selecione um personagem");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       
        String lista = Banco.visualizarListaDeMagias(campoNomeDoPersonagem.getText());
     //  JOptionPane.showMessageDialog(campoListaDeMagia,lista);
       campoListaDeMagia.setText(lista);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       if(campoParaColocarONomeDaMagia.getText().equals("id da magia") || campoParaColocarONomeDaMagia.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Coloca o id meoooooo");
       }else{
        Banco.visualisarMagia(Integer.parseInt(campoParaColocarONomeDaMagia.getText()));
    }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(campoNomeDoPersonagem.getText().equals("personagem")){
        JOptionPane.showMessageDialog(this,"Crie e selecione um personagem primeiro para depois editar");
        }else{
          
        Ficha.editar = true;
        
        CriadorDePersonagem c = new CriadorDePersonagem();
        c.setVisible(true);
        
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void campoParaIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoParaIdMouseClicked
        campoParaId.setText(null);
    }//GEN-LAST:event_campoParaIdMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        campoParaId.setText("colocar id do personagem");
        campoParaColocarONomeDaMagia.setText("id da magia");
    }//GEN-LAST:event_formMouseClicked

    private void campoParaColocarONomeDaMagiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoParaColocarONomeDaMagiaMouseClicked
        campoParaColocarONomeDaMagia.setText(null);
    }//GEN-LAST:event_campoParaColocarONomeDaMagiaMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ficha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VidaDosMaximo;
    private javax.swing.JLabel campoCarisma;
    private javax.swing.JLabel campoClasse;
    private javax.swing.JLabel campoConstituicao;
    private javax.swing.JLabel campoDex;
    private javax.swing.JLabel campoForca;
    private javax.swing.JLabel campoInteligencia;
    private javax.swing.JLabel campoListaDeMagia;
    private javax.swing.JLabel campoModCha;
    private javax.swing.JLabel campoModCons;
    private javax.swing.JLabel campoModDex;
    private javax.swing.JLabel campoModInt;
    private javax.swing.JLabel campoModSab;
    private javax.swing.JLabel campoModStr;
    private javax.swing.JLabel campoNivel;
    private javax.swing.JLabel campoNomeDoJogador;
    private javax.swing.JLabel campoNomeDoPersonagem;
    private javax.swing.JTextField campoParaColocarONomeDaMagia;
    private javax.swing.JTextField campoParaId;
    private javax.swing.JLabel campoRaca;
    private javax.swing.JLabel campoSabedoria;
    private javax.swing.JLabel campoVida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel numeroIndicaVidaChange;
    // End of variables declaration//GEN-END:variables
}
